2024-05-07 11:06:44,405, Controller_RRT.py, 132, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 119, in calculate_path
    Nodes.append(self.start_x, self.start_y)
TypeError: list.append() takes exactly one argument (2 given)
2024-05-07 11:06:44,496, Controller_RRT.py, 89, Error inside run
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 79, in run
    for path in scaled_paths:
TypeError: 'NoneType' object is not iterable
2024-05-07 11:12:17,038, Controller_RRT.py, 137, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 124, in calculate_path
    optimized_nodes = self.optimizer.optimize_path(convert_flat_list_to_tuples(flat_nodes), method="visibility")
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 101, in optimize_path
    if self.is_visible(optimized_path[-1], path[i]):
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 53, in is_visible
    dx = p2[0] - p1[0]
TypeError: unsupported operand type(s) for -: 'list' and 'list'
2024-05-07 11:12:22,878, Controller_RRT.py, 137, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 113, in calculate_path
    Nodes = self.RRT_Algorithm.RRT(img_gray, img_color, self.Calculating_Coords, self.stepSize)
  File "/home/koen/git/Delta/Pathplanning/RRT/rrt.py", line 120, in RRT
    nearest_ind = self.nearest_node(nx,ny)
  File "/home/koen/git/Delta/Pathplanning/RRT/rrt.py", line 83, in nearest_node
    dist,_ = self.dist_and_angle(x,y,self.node_list[i].x,self.node_list[i].y)
AttributeError: 'int' object has no attribute 'x'
2024-05-07 11:13:41,915, Controller_RRT.py, 137, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 124, in calculate_path
    optimized_nodes = self.optimizer.optimize_path(convert_flat_list_to_tuples(flat_nodes), method="visibility")
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 101, in optimize_path
    if self.is_visible(optimized_path[-1], path[i]):
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 53, in is_visible
    dx = p2[0] - p1[0]
TypeError: unsupported operand type(s) for -: 'list' and 'list'
2024-05-07 11:13:47,802, Controller_RRT.py, 137, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 124, in calculate_path
    optimized_nodes = self.optimizer.optimize_path(convert_flat_list_to_tuples(flat_nodes), method="visibility")
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 101, in optimize_path
    if self.is_visible(optimized_path[-1], path[i]):
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 53, in is_visible
    dx = p2[0] - p1[0]
TypeError: unsupported operand type(s) for -: 'list' and 'list'
2024-05-07 11:13:53,713, Controller_RRT.py, 137, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 124, in calculate_path
    optimized_nodes = self.optimizer.optimize_path(convert_flat_list_to_tuples(flat_nodes), method="visibility")
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 101, in optimize_path
    if self.is_visible(optimized_path[-1], path[i]):
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 53, in is_visible
    dx = p2[0] - p1[0]
TypeError: unsupported operand type(s) for -: 'list' and 'list'
2024-05-07 11:13:59,611, Controller_RRT.py, 137, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 124, in calculate_path
    optimized_nodes = self.optimizer.optimize_path(convert_flat_list_to_tuples(flat_nodes), method="visibility")
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 101, in optimize_path
    if self.is_visible(optimized_path[-1], path[i]):
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 53, in is_visible
    dx = p2[0] - p1[0]
TypeError: unsupported operand type(s) for -: 'list' and 'list'
2024-05-07 11:14:05,525, Controller_RRT.py, 137, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 124, in calculate_path
    optimized_nodes = self.optimizer.optimize_path(convert_flat_list_to_tuples(flat_nodes), method="visibility")
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 101, in optimize_path
    if self.is_visible(optimized_path[-1], path[i]):
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 53, in is_visible
    dx = p2[0] - p1[0]
TypeError: unsupported operand type(s) for -: 'list' and 'list'
2024-05-07 11:14:11,419, Controller_RRT.py, 137, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 124, in calculate_path
    optimized_nodes = self.optimizer.optimize_path(convert_flat_list_to_tuples(flat_nodes), method="visibility")
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 101, in optimize_path
    if self.is_visible(optimized_path[-1], path[i]):
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 53, in is_visible
    dx = p2[0] - p1[0]
TypeError: unsupported operand type(s) for -: 'list' and 'list'
2024-05-07 11:14:17,308, Controller_RRT.py, 137, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 124, in calculate_path
    optimized_nodes = self.optimizer.optimize_path(convert_flat_list_to_tuples(flat_nodes), method="visibility")
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 101, in optimize_path
    if self.is_visible(optimized_path[-1], path[i]):
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 53, in is_visible
    dx = p2[0] - p1[0]
TypeError: unsupported operand type(s) for -: 'list' and 'list'
2024-05-07 11:15:01,833, Controller_RRT.py, 138, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 114, in calculate_path
    print(f"Nodes: {Nodes.parent_x}, {Nodes.parent_y}")
AttributeError: 'list' object has no attribute 'parent_x'
2024-05-07 11:15:33,526, Controller_RRT.py, 138, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 114, in calculate_path
    print(f"Nodes: {Nodes.parent_x}, {Nodes.parent_y}")
AttributeError: 'list' object has no attribute 'parent_x'
2024-05-07 11:16:00,867, Controller_RRT.py, 137, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 124, in calculate_path
    optimized_nodes = self.optimizer.optimize_path(convert_flat_list_to_tuples(flat_nodes), method="visibility")
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 101, in optimize_path
    if self.is_visible(optimized_path[-1], path[i]):
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 53, in is_visible
    dx = p2[0] - p1[0]
TypeError: unsupported operand type(s) for -: 'list' and 'list'
2024-05-07 11:20:15,240, Controller_RRT.py, 85, Error inside run
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 66, in run
    scaled_paths = self.scale_coordinates(nodes, scale_factor_x, scale_factor_y)
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 157, in scale_coordinates
    scaled_path = [(x * scale_factor_x - difference, y * scale_factor_y - difference) for x, y in path]
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 157, in <listcomp>
    scaled_path = [(x * scale_factor_x - difference, y * scale_factor_y - difference) for x, y in path]
TypeError: cannot unpack non-iterable int object
2024-05-07 11:31:07,499, Controller_RRT.py, 85, Error inside run
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 66, in run
    scaled_paths = self.scale_coordinates(nodes, scale_factor_x, scale_factor_y)
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 156, in scale_coordinates
    scaled_path = [(x * scale_factor_x - difference, y * scale_factor_y - difference) for x, y in path]
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 156, in <listcomp>
    scaled_path = [(x * scale_factor_x - difference, y * scale_factor_y - difference) for x, y in path]
TypeError: cannot unpack non-iterable numpy.float64 object
2024-05-07 11:38:03,574, Controller_RRT.py, 141, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 127, in calculate_path
    optimized_nodes = self.optimizer.optimize_path(flat_nodes, method="closest_point")
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 104, in optimize_path
    new_position = self.closest_black_pixel(path[i])
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 78, in closest_black_pixel
    for x in range(p[0] - search_radius, p[0] + search_radius + 1):
TypeError: 'numpy.float64' object cannot be interpreted as an integer
2024-05-07 11:38:21,656, Controller_RRT.py, 141, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 127, in calculate_path
    optimized_nodes = self.optimizer.optimize_path(flat_nodes, method="closest_point")
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 104, in optimize_path
    new_position = self.closest_black_pixel(path[i])
  File "/home/koen/git/Delta/Pathplanning/PathOptimize.py", line 78, in closest_black_pixel
    for x in range(p[0] - search_radius, p[0] + search_radius + 1):
TypeError: 'numpy.float64' object cannot be interpreted as an integer
2024-05-07 12:03:26,455, Controller_RRT.py, 141, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 113, in calculate_path
    _, x_list, y_list = self.RRT_Algorithm.RRT(img_gray, img_color, self.Calculating_Coords, self.stepSize)
ValueError: not enough values to unpack (expected 3, got 2)
2024-05-07 12:03:37,048, Controller_RRT.py, 141, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 113, in calculate_path
    _, x_list, y_list = self.RRT_Algorithm.RRT(img_gray, img_color, self.Calculating_Coords, self.stepSize)
ValueError: not enough values to unpack (expected 3, got 2)
2024-05-07 12:05:40,298, Controller_RRT.py, 141, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 113, in calculate_path
    _, x_list, y_list = self.RRT_Algorithm.RRT(img_gray, img_color, self.Calculating_Coords, self.stepSize)
ValueError: not enough values to unpack (expected 3, got 2)
2024-05-07 12:06:07,159, Controller_RRT.py, 141, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 113, in calculate_path
    _, x_list, y_list = self.RRT_Algorithm.RRT(img_gray, img_color, self.Calculating_Coords, self.stepSize)
ValueError: not enough values to unpack (expected 3, got 2)
2024-05-07 12:56:01,802, Controller_RRT.py, 140, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 114, in calculate_path
    _, x_list, y_list = self.RRT_Algorithm.RRT(img_gray, img_color, self.Calculating_Coords, self.stepSize)
  File "/home/koen/git/Delta/Pathplanning/RRT/rrt.py", line 114, in RRT
    self.x_list.append(self.node_list[i].parent_x[i])
IndexError: list index out of range
2024-05-07 12:56:16,030, Controller_RRT.py, 140, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 114, in calculate_path
    _, x_list, y_list = self.RRT_Algorithm.RRT(img_gray, img_color, self.Calculating_Coords, self.stepSize)
  File "/home/koen/git/Delta/Pathplanning/RRT/rrt.py", line 114, in RRT
    self.x_list.append(self.node_list[i].parent_x[i])
IndexError: list index out of range
2024-05-07 13:01:51,959, Controller_RRT.py, 140, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 114, in calculate_path
    _, x_list, y_list = self.RRT_Algorithm.RRT(img_gray, img_color, self.Calculating_Coords, self.stepSize)
  File "/home/koen/git/Delta/Pathplanning/RRT/rrt.py", line 116, in RRT
    self.x_list.append(self.node_list[i].parent_x[i])
IndexError: list index out of range
2024-05-07 13:02:28,499, Controller_RRT.py, 140, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 114, in calculate_path
    _, x_list, y_list = self.RRT_Algorithm.RRT(img_gray, img_color, self.Calculating_Coords, self.stepSize)
  File "/home/koen/git/Delta/Pathplanning/RRT/rrt.py", line 116, in RRT
    self.x_list.append(self.node_list[i].parent_x[i])
IndexError: list index out of range
2024-05-07 13:05:27,313, Controller_RRT.py, 140, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 117, in calculate_path
    x_list.append(0, self.Calculating_Coords[2])
TypeError: list.append() takes exactly one argument (2 given)
2024-05-07 13:22:56,454, Controller_RRT.py, 142, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 128, in calculate_path
    optimized_nodes = self.optimizer.optimize_path(flat_nodes, method="visibility")
TypeError: PathOptimizer.optimize_path() got an unexpected keyword argument 'method'
2024-05-07 13:23:02,371, Controller_RRT.py, 142, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 128, in calculate_path
    optimized_nodes = self.optimizer.optimize_path(flat_nodes, method="visibility")
TypeError: PathOptimizer.optimize_path() got an unexpected keyword argument 'method'
2024-05-07 13:24:06,420, Controller_RRT.py, 142, Error inside calculate_path
Traceback (most recent call last):
  File "/home/koen/git/Delta/Pathplanning/Controller_RRT.py", line 114, in calculate_path
    _, x_list, y_list = self.RRT_Algorithm.RRT(img_gray, img_color, self.Calculating_Coords, self.stepSize)
  File "/home/koen/git/Delta/Pathplanning/RRT/rrt.py", line 93, in RRT
    tx, ty, directCon, nodeCon = self.check_collision(nx, ny, nearest_x, nearest_y, stepSize)
  File "/home/koen/git/Delta/Pathplanning/RRT/rrt.py", line 41, in check_collision
    if self.collision(x, y, self.end[0], self.end[1]):
  File "/home/koen/git/Delta/Pathplanning/RRT/rrt.py", line 22, in collision
    x = list(np.arange(x1, x2, (x2 - x1) / 100))
ValueError: arange: cannot compute length
